inherit_from: "configs/mono/kitti/base_config.yaml"

Dataset:
  color_path: "/media/deng/Data/KITTIdataset/data_odometry_color/dataset/sequences/00/image_2"
  Calibration:
    fx: 7.188560000000e+02
    fy: 7.188560000000e+02
    cx: 6.071928000000e+02
    cy: 1.852157000000e+02
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 1241
    height: 376
    distorted: False

SLAM:
  motion_thresh: 26.0 
  loop_closure: True
